kind: pipeline
type: docker
name: deploy-example

trigger:
  branch:
  - main
  event:
  - push

steps:
- name: install
  image: node:18
  commands:
  - npm install

- name: build
  image: node:18
  commands:
  - npm run build
  - npm run build:example
  - echo "--- BUILT FILES ---"
  - ls -R docs

- name: publish
  image: appleboy/drone-gh-pages
  settings:
    username: git
    password:
      from_secret: github_token
    source: docs
    target_branch: gh-pages
    commit_message: "feat(docs): publish example app to github pages"
  when:
    event: push 